version: "3"

networks:
  network:

services:
  council.lei.net:
    container_name: council.lei.net
    extends:
      file: docker-base.yaml
      service: ca-base
    command: sh -c 'fabric-ca-server start -d -b ca-admin:ca-adminpw --port 7050'
    environment:
      - FABRIC_CA_SERVER_CSR_CN=council.lei.net
      - FABRIC_CA_SERVER_CSR_HOSTS=council.lei.net
    volumes:
      - ${LOCAL_CA_PATH}/council.lei.net/ca:${DOCKER_CA_PATH}/ca
    ports:
      - 7050:7050

  org1.lei.net:
    container_name: org1.lei.net
    extends:
      file: docker-base.yaml
      service: ca-base
    command: sh -c 'fabric-ca-server start -d -b ca-admin:ca-adminpw --port 7050'
    environment:
      - FABRIC_CA_SERVER_CSR_CN=org1.lei.net
      - FABRIC_CA_SERVER_CSR_HOSTS=org1.lei.net
    volumes:
      - ${LOCAL_CA_PATH}/org1.lei.net/ca:${DOCKER_CA_PATH}/ca
    ports:
      - 7250:7050

  org3.lei.net:
    container_name: org3.lei.net
    extends:
      file: docker-base.yaml
      service: ca-base
    command: sh -c 'fabric-ca-server start -d -b ca-admin:ca-adminpw --port 7050'
    environment:
      - FABRIC_CA_SERVER_CSR_CN=org3.lei.net
      - FABRIC_CA_SERVER_CSR_HOSTS=org3.lei.net
    volumes:
      - ${LOCAL_CA_PATH}/org3.lei.net/ca:${DOCKER_CA_PATH}/ca
    ports:
      - 7350:7050
  
  org2.lei.net:
    container_name: org2.lei.net
    extends:
      file: docker-base.yaml
      service: ca-base
    command: sh -c 'fabric-ca-server start -d -b ca-admin:ca-adminpw --port 7050'
    environment:
      - FABRIC_CA_SERVER_CSR_CN=org2.lei.net
      - FABRIC_CA_SERVER_CSR_HOSTS=org2.lei.net
    volumes:
      - ${LOCAL_CA_PATH}/org2.lei.net/ca:${DOCKER_CA_PATH}/ca
    ports:
      - 7450:7050

  org4.lei.net:
    container_name: org4.lei.net
    extends:
      file: docker-base.yaml
      service: ca-base
    command: sh -c 'fabric-ca-server start -d -b ca-admin:ca-adminpw --port 7050'
    environment:
      - FABRIC_CA_SERVER_CSR_CN=org4.lei.net
      - FABRIC_CA_SERVER_CSR_HOSTS=org4.lei.net
    volumes:
      - ${LOCAL_CA_PATH}/org4.lei.net/ca:${DOCKER_CA_PATH}/ca
    ports:
      - 7550:7050

  org5.lei.net:
    container_name: org5.lei.net
    extends:
      file: docker-base.yaml
      service: ca-base
    command: sh -c 'fabric-ca-server start -d -b ca-admin:ca-adminpw --port 7050'
    environment:
      - FABRIC_CA_SERVER_CSR_CN=org5.lei.net
      - FABRIC_CA_SERVER_CSR_HOSTS=org5.lei.net
    volumes:
      - ${LOCAL_CA_PATH}/org5.lei.net/ca:${DOCKER_CA_PATH}/ca
    ports:
      - 7650:7050

  peer1.org1.lei.net:
    container_name: peer1.org1.lei.net
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.lei.net
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7251
      - CORE_PEER_ADDRESS=peer1.org1.lei.net:7251
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.lei.net:7251
    volumes:
      - ${LOCAL_CA_PATH}/org1.lei.net/registers/peer1:${DOCKER_CA_PATH}/peer
    ports:
      - 7251:7251
    cpu_count: 1
    cpu_period: 100000
    cpu_quota: 50000
    cpuset: 0,0
      
  peer1.org3.lei.net:
    container_name: peer1.org3.lei.net
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.lei.net
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7351
      - CORE_PEER_ADDRESS=peer1.org3.lei.net:7351
      - CORE_PEER_LOCALMSPID=org3MSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.lei.net:7351
    volumes:
      - ${LOCAL_CA_PATH}/org3.lei.net/registers/peer1:${DOCKER_CA_PATH}/peer
    ports:
      - 7351:7351
    cpu_count: 1
    cpu_period: 100000
    cpu_quota: 50000
    cpuset: 1,1
  peer1.org2.lei.net:
    container_name: peer1.org2.lei.net
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.lei.net
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7451
      - CORE_PEER_ADDRESS=peer1.org2.lei.net:7451
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.lei.net:7451
    volumes:
      - ${LOCAL_CA_PATH}/org2.lei.net/registers/peer1:${DOCKER_CA_PATH}/peer
    ports:
      - 7451:7451
    cpu_count: 1
    cpu_period: 100000
    cpu_quota: 50000
    cpuset: 2,2      
  peer1.org4.lei.net:
    container_name: peer1.org4.lei.net
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org4.lei.net
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7551
      - CORE_PEER_ADDRESS=peer1.org4.lei.net:7551
      - CORE_PEER_LOCALMSPID=org4MSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org4.lei.net:7551
    volumes:
      - ${LOCAL_CA_PATH}/org4.lei.net/registers/peer1:${DOCKER_CA_PATH}/peer
    ports:
      - 7551:7551
    cpu_count: 1
    cpu_period: 100000
    cpu_quota: 50000
    cpuset: 3,3   
  peer1.org5.lei.net:
    container_name: peer1.org5.lei.net
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org5.lei.net
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7651
      - CORE_PEER_ADDRESS=peer1.org5.lei.net:7651
      - CORE_PEER_LOCALMSPID=org5MSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org5.lei.net:7651
    volumes:
      - ${LOCAL_CA_PATH}/org5.lei.net/registers/peer1:${DOCKER_CA_PATH}/peer
    ports:
      - 7651:7651
    cpu_count: 1
    cpu_period: 100000
    cpu_quota: 50000
    cpuset: 3,3       

  orderer1.council.lei.net:
    container_name: orderer1.council.lei.net
    extends:
      file: docker-base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=orderer1.council.lei.net
      - ORDERER_GENERAL_LOCALMSPID=councilMSP
      - ORDERER_GENERAL_LISTENPORT=7051
    volumes:
      - ${LOCAL_CA_PATH}/council.lei.net/registers/orderer1:${DOCKER_CA_PATH}/orderer
    ports:
      - 7051:7051
      - 7052:8888
      - 7053:9999

  orderer2.council.lei.net:
    container_name: orderer2.council.lei.net
    extends:
      file: docker-base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=orderer2.council.lei.net
      - ORDERER_GENERAL_LOCALMSPID=councilMSP
      - ORDERER_GENERAL_LISTENPORT=7054
    volumes:
      - ${LOCAL_CA_PATH}/council.lei.net/registers/orderer2:${DOCKER_CA_PATH}/orderer
    ports:
      - 7054:7054
      - 7055:8888
      - 7056:9999
      
  orderer3.council.lei.net:
    container_name: orderer3.council.lei.net
    extends:
      file: docker-base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=orderer3.council.lei.net
      - ORDERER_GENERAL_LOCALMSPID=councilMSP
      - ORDERER_GENERAL_LISTENPORT=7057
    volumes:
      - ${LOCAL_CA_PATH}/council.lei.net/registers/orderer3:${DOCKER_CA_PATH}/orderer
    ports:
      - 7057:7057
      - 7058:8888
      - 7059:9999

  # orderer4.council.lei.net:
  #   container_name: orderer4.council.lei.net
  #   extends:
  #     file: docker-base.yaml
  #     service: orderer-base
  #   environment:
  #     - ORDERER_HOST=orderer4.council.lei.net
  #     - ORDERER_GENERAL_LOCALMSPID=councilMSP
  #     - ORDERER_GENERAL_LISTENPORT=7060
  #   volumes:
  #     - ${LOCAL_CA_PATH}/council.lei.net/registers/orderer4:${DOCKER_CA_PATH}/orderer
  #   ports:
  #     - 7060:7060
  #     - 7061:8888
  #     - 7062:9999

  # orderer5.council.lei.net:
    container_name: orderer5.council.lei.net
    extends:
      file: docker-base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=orderer5.council.lei.net
      - ORDERER_GENERAL_LOCALMSPID=councilMSP
      - ORDERER_GENERAL_LISTENPORT=7063
    volumes:
      - ${LOCAL_CA_PATH}/council.lei.net/registers/orderer5:${DOCKER_CA_PATH}/orderer
    ports:
      - 7063:7063
      - 7064:8888
      - 7065:9999      