server:
  port: 9001

spring:
  application:
    name: client-java
knife4j:
  enable: true
  openapi:
    title: hcp-abac
    description: "访问控制java应用代码"
    email: 1539863706@qq.com
    concat: lei
    url: https://www.baidu.com
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/

fabric:
  # wallet文件夹路径(自动创建)
  walletDirectory: wallet
  # 网络配置文件路径
  networkConfigPath: E:/code/orgs/soft.ifantasy.net/connection-soft.yaml
  # 用户证书路径
  #certificatePath: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
  #certificatePath: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem
  certificatePath: E:/code/orgs/soft.ifantasy.net/registers/user1/msp/signcerts/cert.pem
  #certificatePath: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem
  # 用户私钥路径
  #privateKeyPath: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
  #privateKeyPath: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/priv_sk
  privateKeyPath: E:/code/orgs/soft.ifantasy.net/registers/user1/msp/keystore/930e9fa63e3ab32e85247370b26260de1af06e4ac10e4c7d341976b39f51aa5e_sk
  # 访问的组织名
  mspid: softMSP
  # 用户名
  username: user1
  # 通道名字
  channelName: testchannel
  # 链码名字
  contractName: abac
logging:
  level:
    org:
      hyperledger:
        fabric:
          info
    root: info
