version: '2'

networks:
  network:

services:
  council.lei.net:
    container_name: council.lei.net
    extends:
      file: docker-base.yaml
      service: ca-base
    command: sh -c 'fabric-ca-server start -d -b ca-admin:ca-adminpw --port 7050'
    environment:
      - FABRIC_CA_SERVER_CSR_CN=council.lei.net
      - FABRIC_CA_SERVER_CSR_HOSTS=council.lei.net
    volumes:
      - ${LOCAL_CA_PATH}/council.lei.net/ca:${DOCKER_CA_PATH}/ca
    ports:
      - 7050:7050

  org1.lei.net:
    container_name: org1.lei.net
    extends:
      file: docker-base.yaml
      service: ca-base
    command: sh -c 'fabric-ca-server start -d -b ca-admin:ca-adminpw --port 7050'
    environment:
      - FABRIC_CA_SERVER_CSR_CN=org1.lei.net
      - FABRIC_CA_SERVER_CSR_HOSTS=org1.lei.net
    volumes:
      - ${LOCAL_CA_PATH}/org1.lei.net/ca:${DOCKER_CA_PATH}/ca
    ports:
      - 7250:7050

  org2.lei.net:
    container_name: org2.lei.net
    extends:
      file: docker-base.yaml
      service: ca-base
    command: sh -c 'fabric-ca-server start -d -b ca-admin:ca-adminpw --port 7050'
    environment:
      - FABRIC_CA_SERVER_CSR_CN=org2.lei.net
      - FABRIC_CA_SERVER_CSR_HOSTS=org2.lei.net
    volumes:
      - ${LOCAL_CA_PATH}/org2.lei.net/ca:${DOCKER_CA_PATH}/ca
    ports:
      - 7450:7050

  peer1.org1.lei.net:
    container_name: peer1.org1.lei.net
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.lei.net
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7251
      - CORE_PEER_ADDRESS=peer1.org1.lei.net:7251
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.lei.net:7251
    volumes:
      - ${LOCAL_CA_PATH}/org1.lei.net/registers/peer1:${DOCKER_CA_PATH}/peer
    ports:
      - 7251:7251
      

  peer1.org2.lei.net:
    container_name: peer1.org2.lei.net
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.lei.net
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7451
      - CORE_PEER_ADDRESS=peer1.org2.lei.net:7451
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.lei.net:7451
    volumes:
      - ${LOCAL_CA_PATH}/org2.lei.net/registers/peer1:${DOCKER_CA_PATH}/peer
    ports:
      - 7451:7451
      
  orderer1.council.lei.net:
    container_name: orderer1.council.lei.net
    extends:
      file: docker-base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=orderer1.council.lei.net
      - ORDERER_GENERAL_LOCALMSPID=councilMSP
      - ORDERER_GENERAL_LISTENPORT=7051
    volumes:
      - ${LOCAL_CA_PATH}/council.lei.net/registers/orderer1:${DOCKER_CA_PATH}/orderer
    ports:
      - 7051:7051
      - 7052:8888
      - 7053:9999

  orderer2.council.lei.net:
    container_name: orderer2.council.lei.net
    extends:
      file: docker-base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=orderer2.council.lei.net
      - ORDERER_GENERAL_LOCALMSPID=councilMSP
      - ORDERER_GENERAL_LISTENPORT=7054
    volumes:
      - ${LOCAL_CA_PATH}/council.lei.net/registers/orderer2:${DOCKER_CA_PATH}/orderer
    ports:
      - 7054:7054
      - 7055:8888
      - 7056:9999
      
  orderer3.council.lei.net:
    container_name: orderer3.council.lei.net
    extends:
      file: docker-base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=orderer3.council.lei.net
      - ORDERER_GENERAL_LOCALMSPID=councilMSP
      - ORDERER_GENERAL_LISTENPORT=7057
    volumes:
      - ${LOCAL_CA_PATH}/council.lei.net/registers/orderer3:${DOCKER_CA_PATH}/orderer
    ports:
      - 7057:7057
      - 7058:8888
      - 7059:9999